# .github/workflows/continuous-integration.yaml

name: 'Continuous Integration'

# This workflow runs on every push to the main branch
# and on every pull request that targets the main branch.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: 'âœ… Checkout Repository'
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - name: 'ğŸ Set up Python 3.11 & Cache Dependencies'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: 'ğŸ“¦ Install Dependencies (including dev)'
        run: poetry install

      - name: 'ğŸ¨ Run Linter (Ruff)'
        run: |
          poetry run ruff check .

      - name: 'ğŸ”’ Run Security Scan (Safety)'
        run: |
          # Ignoring vulnerabilities related to deserialization in MLflow,
          # as we are in a controlled environment.
          poetry run safety check \
            --ignore=60492 \
            --ignore=71691 \
            --ignore=71692 \
            --ignore=77891 \
            --ignore=71579 \
            --ignore=71577 \
            --ignore=71578 \
            --ignore=71693 \
            --ignore=71587 \
            --ignore=71584

      - name: 'ğŸ§ª Run Unit Tests (Pytest)'
        run: |
          poetry run pytest
